@Library('shared_library') _

pipeline {
    agent any

    stages {

        stage('Shared Library') {
            steps {
                script {
                    sayHello()
                }
            }
        }

        stage('Create Artifacts') {
            steps {
                sh '''
                echo "Firmware Binary" > firmware.bin
                echo "Firmware ELF" > firmware.elf
                echo "Firmware HEX" > firmware.hex
                echo "Formatting Report" > clang-format-report.txt
                '''
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '*.bin,*.elf,*.hex,*.txt', fingerprint: true
            }
        }
    }
}
