pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
            }
        }

        stage('Configure') {
    steps {
        dir('led-firmware') {
            sh '''
                mkdir -p build
                cd build
                cmake ..
            '''
        }
    }
}

        stage('Build') {
            steps {
                sh '''
                cd build
                make
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Build Successful'
            }
        }
    }
}


