pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
            }
        }

        stage('Configure') {
            steps {
                dir('led-firmware') {
                    sh '''
                        mkdir -p build
                        cd build
                        cmake ..
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                dir('led-firmware') {
                    sh '''
                        cd build
                        make
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('led-firmware') {
                    sh '''
                        cd build
                        ctest
                    '''
                }
            }
        }

    }   // closes stages

}   // closes pipeline
